# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  ImageName: 'aaditya7789/maventest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and push Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Get short git hash
      env: { sourceVersion: $(Build.SourceVersion) }
      inputs:
        targetType: 'inline'
        script: |
          echo $sourceVersion
          commitHash=${sourceVersion:0:8}
          echo $commitHash
          echo "##vso[task.setvariable variable=commitHash]$commitHash"
    - task: Docker@2
      displayName: Build and Push docker image
      inputs:
        command: buildAndPush
        repository: $(ImageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: dockerhub
        tags: |
          $(commitHash)
        
