version: 0.2

env:
  shell: bash
  secrets-manager:
    DOCKERHUB_USERNAME: docker_secrets:DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD: docker_secrets:DOCKERHUB_PASSWORD
    DOCKERHUB_REPOSITORY: docker_secrets:DOCKERHUB_REPOSITORY

phases:
  pre_build:
    commands:
      - echo "Logging into DOCKERHUB.."
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo "Building a Docker image.."
      - docker build -t $DOCKERHUB_REPOSITORY:${CODEBUILD_RESOLVED_SOURCE_VERSION::8} .
  post_build:
    commands:
      - echo "Pushing Docker image to DOCKERHUB.."
      - docker push $DOCKERHUB_REPOSITORY:${CODEBUILD_RESOLVED_SOURCE_VERSION::8}

