version: 0.2

env:
  shell: bash
  secrets-manager:
    DOCKERHUB_USERNAME: Aaditya_docker_secrets:DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD: Aaditya_docker_secrets:DOCKERHUB_PASSWORD
    DOCKERHUB_REPOSITORY: Aaditya_docker_secrets:DOCKERHUB_REPOSITORY

phases:
  pre_build:
    command:
      - echo "Logging into DOCKERHUB.."
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo "Building a Docker image.."
      - docker build -t $DOCKERHUB_REPOSITORY:$CODEBUILD_BUILD_ID .
  post_build:
    commands:
      - echo "Pushing Docker image to DOCKERHUB.."
      - docker push $DOCKERHUB_REPOSITORY:$CODEBUILD_BUILD_ID

